FROM python:3.8

RUN apt-get update
RUN apt-get install -y libsnappy-dev

# dask/tests/test_config.py::test_collect_yaml_permission_errors fails as root
# because it relies on a certain path being unreadable
RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user
ENV PATH="/home/user/.local/bin:$PATH"
RUN pip install --upgrade pip
RUN git clone https://github.com/dask/dask.git
WORKDIR dask
ARG dask_version
RUN git checkout "$dask_version"
RUN pip install pytest
